
spring:
  datasource:
    url: jdbc:mysql://192.168.0.106:3306/tmall_springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: learn
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false


