
spring:
  datasource:
    url: jdbc:mysql://192.168.0.106:3306/tmall_springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: learn
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10
        max-wait: -1 # means unlimited
        max-idle: 8
        min-idle: 0
    timeout: 0
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300